name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # PlombiPro Dependencies
  firebase_core: ^2.31.0
  supabase_flutter: ^2.5.3

  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  pdf: ^3.11.0
  intl: ^0.20.2
  dio: ^5.5.0+1
  http: ^1.2.1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  go_router: ^14.1.4
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  signature: ^5.5.0
  flutter_stripe: ^10.1.1

  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  uuid: ^4.4.0
  json_annotation: ^4.9.0
  sentry_flutter: ^8.11.1
  excel: ^4.0.6
  csv: ^6.0.0
  introduction_screen: ^3.1.14
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # PlombiPro Dev Dependencies
  build_runner: ^2.4.9
  freezed: ^2.5.2

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/templates/