name: Test

on: push

jobs:
  build:
    runs-on: ${{ mac.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Extract zip
        uses: ./
        with:
          file_path: ./Obat+_+devis+facture+baÌ‚timent_1.0.33_apkcombo.com.zip
          extract_dir: ./zip
          verbose: true
